version: "1.0"
info:
  model: int-scaffold
packages:
- name: SiqaDemoTesTScafProject
  gitServerName: siqagituser
  gitUrl: https://github.com/siqagituser
  gitUsername: siqagituser
  gitBranch: main
